import FluentKit
import FluentSQL
import NIOEmbedded
import SQLKit
import XCTFluent
import NIOConcurrencyHelpers

public final class DummyDatabaseForTestSQLSerializer: Database, SQLDatabase {
    public var inTransaction: Bool {
        false
    }

    struct Configuration: DatabaseConfiguration {
        func makeDriver(for databases: Databases) -> any DatabaseDriver {
            fatalError()
        }

        var middleware: [any AnyModelMiddleware] = []
    }

    public var dialect: any SQLDialect {
        DummyDatabaseDialect()
    }

    public let context: DatabaseContext

    let _sqlSerializers = NIOLockedValueBox<[SQLSerializer]>([])
    public var sqlSerializers: [SQLSerializer] {
        get { self._sqlSerializers.withLockedValue { $0 } }
        set { self._sqlSerializers.withLockedValue { $0 = newValue } }
    }

    public init() {
        self.context = .init(
            configuration: Configuration(),
            logger: .init(label: "test"),
            eventLoop: EmbeddedEventLoop()
        )
    }

    public func reset() {
        self.sqlSerializers = []
    }
    
    public func execute(
        query: DatabaseQuery,
        onOutput: @escaping @Sendable (any DatabaseOutput) -> ()
    ) -> EventLoopFuture<Void> {
        var sqlSerializer = SQLSerializer(database: self)
        let sqlExpression = SQLQueryConverter(delegate: DummyDatabaseConverterDelegate()).convert(query)
        sqlExpression.serialize(to: &sqlSerializer)
        self.sqlSerializers.append(sqlSerializer)
        onOutput(DummyRow())
        return self.eventLoop.makeSucceededFuture(())
    }

    public func execute(sql query: any SQLExpression, _ onRow: @escaping @Sendable (any SQLRow) -> ()) -> EventLoopFuture<Void> {
        fatalError()
    }

    public func transaction<T>(_ closure: @escaping @Sendable (any Database) -> EventLoopFuture<T>) -> EventLoopFuture<T> {
        closure(self)
    }
    
    public func execute(schema: DatabaseSchema) -> EventLoopFuture<Void> {
        var sqlSerializer = SQLSerializer(database: self)
        let sqlExpression = SQLSchemaConverter(delegate: DummyDatabaseConverterDelegate()).convert(schema)
        sqlExpression.serialize(to: &sqlSerializer)
        self.sqlSerializers.append(sqlSerializer)
        return self.eventLoop.makeSucceededFuture(())
    }

    public func execute(enum: DatabaseEnum) -> EventLoopFuture<Void> {
        // do nothing
        self.eventLoop.makeSucceededFuture(())
    }
    
    public func withConnection<T>(
        _ closure: @escaping @Sendable (any Database) -> EventLoopFuture<T>
    ) -> EventLoopFuture<T> {
        closure(self)
    }

    public func shutdown() {
        //
    }
}

// Copy from PostgresDialect
struct DummyDatabaseDialect: SQLDialect {
    var supportsAutoIncrement: Bool {
        true
    }

    var enumSyntax: SQLEnumSyntax {
        .unsupported
    }

    var name: String {
        "dummy db"
    }

    var identifierQuote: any SQLExpression {
        SQLRaw("\"")
    }

    var literalStringQuote: any SQLExpression {
        SQLRaw("'")
    }

    func bindPlaceholder(at position: Int) -> any SQLExpression {
        SQLRaw("$" + position.description)
    }

    func literalBoolean(_ value: Bool) -> any SQLExpression {
        SQLRaw(value ? "true" : "false")
    }

    var autoIncrementClause: any SQLExpression {
        SQLRaw("GENERATED BY DEFAULT AS IDENTITY")
    }
    
    var sharedSelectLockExpression: (any SQLExpression)? {
        SQLRaw("FOR SHARE")
    }

    var exclusiveSelectLockExpression: (any SQLExpression)? {
        SQLRaw("FOR UPDATE")
    }
}

// Copy from PostgresConverterDelegate
struct DummyDatabaseConverterDelegate: SQLConverterDelegate {
    func customDataType(_ dataType: DatabaseSchema.DataType) -> (any SQLExpression)? {
        switch dataType {
        case .uuid:
            return SQLRaw("UUID")
        case .bool:
            return SQLRaw("BOOL")
        case .data:
            return SQLRaw("BYTEA")
        case .datetime:
            return SQLRaw("TIMESTAMPTZ")
        default:
            return nil
        }
    }

    func nestedFieldExpression(_ column: String, _ path: [String]) -> any SQLExpression {
        SQLRaw("\(column)->>'\(path[0])'")
    }
}
