import FluentKit
import NIO
import SQLKit
import FluentSQL

public class DummyDatabaseForTestSQLSerializer: Database {
    public var sqlSerializers: [SQLSerializer]
    
    /// See `FluentDatabase`.
    public var eventLoop: EventLoop {
        return EmbeddedEventLoop()
    }

    public init() {
        self.sqlSerializers = []
    }
    
    /// See `FluentDatabase`.
    public func execute(_ query: DatabaseQuery, _ onOutput: @escaping (DatabaseOutput) throws -> ()) -> EventLoopFuture<Void> {
        var sqlSerializer = SQLSerializer(dialect: DummyDatabaseDialect())
        let sqlExpression = SQLQueryConverter(delegate: DummyDatabaseConverterDelegate()).convert(query)
        sqlExpression.serialize(to: &sqlSerializer)
        self.sqlSerializers.append(sqlSerializer)
        
        return self.eventLoop.makeSucceededFuture(())
    }
    
    /// See `FluentDatabase`.
    public func execute(_ schema: DatabaseSchema) -> EventLoopFuture<Void> {
        return self.eventLoop.makeSucceededFuture(())
    }
    
    public func close() -> EventLoopFuture<Void> {
        return self.eventLoop.makeSucceededFuture(())
    }
    
    public func withConnection<T>(_ closure: @escaping (Database) -> EventLoopFuture<T>) -> EventLoopFuture<T> {
        return closure(self)
    }
}

// Copy from PostgresDialect
struct DummyDatabaseDialect: SQLDialect {
    private var bindOffset: Int

    init() {
        self.bindOffset = 0
    }

    var identifierQuote: SQLExpression {
        return SQLRaw("\"")
    }

    var literalStringQuote: SQLExpression {
        return SQLRaw("'")
    }

    mutating func nextBindPlaceholder() -> SQLExpression {
        self.bindOffset += 1
        return SQLRaw("$" + self.bindOffset.description)
    }

    func literalBoolean(_ value: Bool) -> SQLExpression {
        switch value {
        case false:
            return SQLRaw("false")
        case true:
            return SQLRaw("true")
        }
    }

    var autoIncrementClause: SQLExpression {
        return SQLRaw("GENERATED BY DEFAULT AS IDENTITY")
    }
}

// Copy from PostgresConverterDelegate
struct DummyDatabaseConverterDelegate: SQLConverterDelegate {
    func customDataType(_ dataType: DatabaseSchema.DataType) -> SQLExpression? {
        switch dataType {
        case .uuid:
            return SQLRaw("UUID")
        case .bool:
            return SQLRaw("BOOL")
        case .data:
            return SQLRaw("BYTEA")
        case .datetime:
            return SQLRaw("TIMESTAMPTZ")
        default:
            return nil
        }
    }

    func nestedFieldExpression(_ column: String, _ path: [String]) -> SQLExpression {
        return SQLRaw("\(column)->>'\(path[0])'")
    }
}
