#if !canImport(ObjectiveC)
import XCTest

extension FluentKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FluentKitTests = [
        ("testStub", testStub),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FluentKitTests.__allTests__FluentKitTests),
    ]
}
#endif
