#if !canImport(ObjectiveC)
import XCTest

extension FluentKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FluentKitTests = [
        ("testStub", testStub),
    ]
}

extension ModelTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ModelTests = [
        ("testBatchInsert", testBatchInsert),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FluentKitTests.__allTests__FluentKitTests),
        testCase(ModelTests.__allTests__ModelTests),
    ]
}
#endif
