#if !canImport(ObjectiveC)
import XCTest

extension FluentKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FluentKitTests = [
        ("testForeignKeyFieldConstraint", testForeignKeyFieldConstraint),
        ("testForeignKeyTableConstraint", testForeignKeyTableConstraint),
        ("testGalaxyPlanetNames", testGalaxyPlanetNames),
        ("testGalaxyPlanetSorts", testGalaxyPlanetSorts),
        ("testIdentifierFieldConstraint", testIdentifierFieldConstraint),
        ("testMigrationLogNames", testMigrationLogNames),
        ("testMultipleFieldConstraint", testMultipleFieldConstraint),
        ("testRequiredFieldConstraint", testRequiredFieldConstraint),
        ("testSQLSchemaCustomIndex", testSQLSchemaCustomIndex),
        ("testUniqueTableConstraint", testUniqueTableConstraint),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(FluentKitTests.__allTests__FluentKitTests),
    ]
}
#endif
